### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by VuzzyM** [dracarys18/TweetBot#29]
Problem with herokuapp:

Log:

022-07-19T16:48:10.142385+00:00 heroku[worker.1]: Starting process with command `./target/release/tweet_bot`
2022-07-19T16:48:10.800592+00:00 heroku[worker.1]: State changed from starting to up
2022-07-19T16:48:10.884084+00:00 app[worker.1]: thread 'main' panicked at 'Missing ACCOUNTS: NotPresent', src/config.rs:24:14
2022-07-19T16:48:10.884099+00:00 app[worker.1]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-07-19T16:48:11.027775+00:00 heroku[worker.1]: Process exited with status 101
2022-07-19T16:48:11.176182+00:00 heroku[worker.1]: State changed from up to crashed
2022-07-19T16:48:11.179858+00:00 heroku[worker.1]: State changed from crashed to starting
2022-07-19T16:48:11.506615+00:00 heroku[worker.1]: Starting process with command `./target/release/tweet_bot`
2022-07-19T16:48:12.245036+00:00 heroku[worker.1]: State changed from starting to up
2022-07-19T16:48:12.379862+00:00 app[worker.1]: thread 'main' panicked at 'Missing ACCOUNTS: NotPresent', src/config.rs:24:14
2022-07-19T16:48:12.379881+00:00 app[worker.1]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-07-19T16:48:12.658455+00:00 heroku[worker.1]: State changed from up to crashed
2022-07-19T16:48:12.508846+00:00 heroku[worker.1]: Process exited with status 101

**Comment by dracarys18** [comment]
Well as it says you have to declads ACCOUNTS env variable either in .env file or heroku environment variable export

**Comment by VuzzyM** [comment]
> Well as it says you have to declads ACCOUNTS env variable either in .env file or heroku environment variable export

Format "@User" or how?

**Comment by dracarys18** [comment]
export ACCOUNTS= "manutd,nasa" like this @VuzzyM

**Comment by VuzzyM** [comment]
> export ACCOUNTS= "manutd,nasa" like this @VuzzyM

2022-07-21T16:01:36.242371+00:00 app[worker.1]: thread 'main' panicked at 'Invalid Chat ID: ParseIntError { kind: InvalidDigit }', src/config.rs:32:14
        

2022-07-21T16:01:36.242392+00:00 app[worker.1]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Invalid chat id, how to fix?

**Comment by VuzzyM** [comment]
> > export ACCOUNTS= "manutd,nasa" like this @VuzzyM
> 
> 2022-07-21T16:01:36.242371+00:00 app[worker.1]: thread 'main' panicked at 'Invalid Chat ID: ParseIntError { kind: InvalidDigit }', src/config.rs:32:14
> 
> 2022-07-21T16:01:36.242392+00:00 app[worker.1]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> Invalid chat id, how to fix?

What kind of chat should I put here?

**Comment by dracarys18** [comment]
@VuzzyM You have to put the chat ID of the telegram chat. Please read the instructions in example.env @VuzzyM

**Comment by VuzzyM** [comment]
> 

I followed the instructions and it didn't work, i used channel, not chat for test.

**Comment by VuzzyM** [comment]
> @VuzzyM You have to put the chat ID of the telegram chat. Please read the instructions in example.env @VuzzyM 

?

**Comment by VuzzyM** [comment]
> @VuzzyM You have to put the chat ID of the telegram chat. Please read the instructions in example.env @VuzzyM

Do you have to add the bot to the chat and after adding the id?

**Comment by VuzzyM** [comment]
@dracarys18 what format should i use? export Chat Id= "-id" from group or chat?
